WebbiSkools.QuizManager/Pages/Roles/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.ViewModels.Roles;

namespace WebbiSkools.QuizManager.Pages.Roles
{
    [Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        public string Message { get; private set; }
        public bool Success { get; private set; }
        public IEnumerable<IdentityRole> Roles { get; set; }
        [BindProperty]
        public RoleCreate RoleCreate { get; set; }


        private RoleManager<IdentityRole> _roleManager;
        public IndexModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            Roles = _roleManager.Roles;
        }
        public void OnGet()
        {
        }

        public async Task OnPostDelete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    Message = "Successfully deleted the role.";
                }
                else
                {
                    ModelState.AddModelError("sth went wrung key", "sth went wrung");
                }
            }
        }

        public async Task<JsonResult> OnPostCreate()
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
                var x = Request.Query["name"];
                try
                {
                    result = await _roleManager.CreateAsync(new IdentityRole(RoleCreate.Name));
                }
                catch (Exception)
                {
                    throw;
                }
                if (result.Succeeded)
                {
                    Message = "Success! Role created!";
                    Success = true;

                }
                else
                {
                    var error = result.Errors.FirstOrDefault();
                    Message = $"Error. {error.Code}: {error.Description}";
                    Success = false;
                }
            }
            else
            {
                Message = "Error has occurred during posting the role. Please review the suggestions below.";
                Success = false;
            }
            return new JsonResult(new
            {
                Success,
                Message
            }); ;
        }

        public IActionResult OnGetRefreshRoleTable()
        {
            Roles = _roleManager.Roles;
            return Partial("_RolesTable", Roles);
        }

    }
}

WebbiSkools.QuizManager/Pages/Roles/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.ViewModels.Roles;
using WebbiSkools.QuizManager.DAL.Entities.Identity;

namespace WebbiSkools.QuizManager.Pages.Roles
{
    [Authorize(Roles = "Admin")]
    public class UpdateModel : PageModel
    {
        [FromQuery]
        public string Id { get; set; }
        [BindProperty]
        public RoleEdit EditModel { get; set; }
        [BindProperty]
        public RoleModification ModificationModel { get; set; }
        public string Message { get; set; }

        private UserManager<QuizManagerUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;
        public UpdateModel(UserManager<QuizManagerUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task OnGet()
        {
            await PopulateModel(Id);
        }

        public async Task<JsonResult> OnPostUpdate(RoleModification model)
        {
            IdentityResult result;
            var addBuilder = new StringBuilder();
            var removeBuilder = new StringBuilder();
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (result.Succeeded)
                        {
                            addBuilder.Append($"Successfully added {user.UserName} to {model.RoleName}. ");
                        }
                        else
                        {
                            addBuilder.Append(result.Errors.Select(x => x.Description).Aggregate(((concat, str) => $"{concat}, {str}")));
                        }
                        //Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (result.Succeeded)
                        {
                            removeBuilder.Append($"Successfully removed {user.UserName} from {model.RoleName}. ");
                        }
                        else
                        {
                            removeBuilder.Append(result.Errors.Select(x => x.Description).Aggregate(((concat, str) => $"{concat}, {str}")));
                        }
                        //Errors(result);
                    }
                }
            }
            return new JsonResult(new
            {
                RoleId = model.RoleId,
                AddMessage = addBuilder.ToString(),
                RemoveMessage = removeBuilder.ToString()
            });
        }

        public async Task<IActionResult> OnGetRefreshMembershipTable(string id)
        {
            await PopulateModel(id);
            return Partial("_MembershipTables", EditModel);
        }

        private async Task PopulateModel(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<QuizManagerUser> members = new List<QuizManagerUser>();
            List<QuizManagerUser> nonMembers = new List<QuizManagerUser>();
            foreach (QuizManagerUser user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            EditModel = new RoleEdit()
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            };
        }
    }
}

WebbiSkools.QuizManager/Pages/Roles/Index.cshtml
@page
@model WebbiSkools.QuizManager.Pages.Roles.IndexModel
@{
	ViewData["Title"] = "Roles";
}


@section Styles
{
	<link rel="stylesheet" href="~/css/Roles/index.css" asp-append-version="true" />
}

<div class="card">
	<div class="card-body">
		<h1 class="display-4">All Roles</h1>
		<a href="#" id="createRole" class="text-success">Create a Role</a>
		<hr class="style-seven" />
		<div id="alertBox" class="alert alert-success"></div>
		<div class="container" id="createCard">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<div class="text-center">
						Create a new Role
						<div>
							<form id="createForm" method="post" asp-page-handler="Create">
								<span class="text-danger" asp-validation-for="RoleCreate.Name"></span>
								<input asp-for="RoleCreate.Name" class="form-control" />
								<button style="margin:1rem;" class="btn btn-primary" type="submit">Create</button>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>
		<div id="rolesTable">
			<partial name="_RolesTable" model="@Model.Roles" />
		</div>
	</div>
</div>

@section Scripts
{
	<script src="~/js/Roles/index.js" asp-append-version="true"></script>
	<partial name="_ValidationScriptsPartial" />
}

WebbiSkools.QuizManager/Pages/Roles/Update.cshtml
@page
@model WebbiSkools.QuizManager.Pages.Roles.UpdateModel
@{
	ViewData["Title"] = "Update";
}

@section Styles
{
	<link rel="stylesheet" href="~/css/Roles/update.css" asp-append-version="true" />
}

<div class="card">
	<div class="card-body">
		<h1 class="display-4">Update Role</h1>
		<a asp-page="Index">Back</a>
		<hr class="style-seven" />
		<div asp-validation-summary="All" class="text-danger"></div>
		<div id="alertBox" class="alert alert-success"></div>

		<form id="updateForm" asp-page-handler="Update" method="post">
			<input type="hidden" name="roleName" value="@Model.EditModel.Role.Name" />
			<input type="hidden" name="roleId" value="@Model.EditModel.Role.Id" />

			<h2>Add To @Model.EditModel.Role.Name</h2>

			<div id="membershipTable">
				<partial name="_MembershipTables" model="@Model.EditModel">
			</div>

			<button type="submit" class="btn btn-primary">Save</button>
		</form>
	</div>
</div>

@section Scripts
{
	<script src="~/js/Roles//update.js" asp-append-version="true"></script>
	<partial name="_ValidationScriptsPartial" />
}

WebbiSkools.QuizManager/Pages/Roles/_MembershipTables.cshtml
@model WebbiSkools.QuizManager.BRL.ViewModels.Roles.RoleEdit


<table class="table table-bordered table-sm">
	@if (Model.NonMembers.Count() == 0)
	{
		<tr><td colspan="2">All Users Are Members</td></tr>
	}
	else
	{
		@foreach (var user in Model.NonMembers)
		{
			<tr>
				<td>@user.UserName</td>
				<td>
					<input type="checkbox" name="AddIds" value="@user.Id">
				</td>
			</tr>
		}
	}
</table>

<h2>Remove From @Model.Role.Name</h2>
<table class="table table-bordered table-sm">
	@if (Model.Members.Count() == 0)
	{
		<tr><td colspan="2">No Users Are Members</td></tr>
	}
	else
	{
		@foreach (var user in Model.Members)
		{
			<tr>
				<td>@user.UserName</td>
				<td>
					<input type="checkbox" name="DeleteIds" value="@user.Id">
				</td>
			</tr>
		}
	}
</table>

WebbiSkools.QuizManager/Pages/Roles/_RolesTable.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

<table class="table table-sm table-bordered table-bordered">
	<tr><th>ID</th><th>Name</th><th>Users</th><th>Update</th><th>Delete</th></tr>
	@foreach (var role in Model)
	{
		<tr>
			<td>@role.Id</td>
			<td>@role.Name</td>
			<td i-role="@role.Id"></td>
			<td><a class="btn btn-sm btn-primary" asp-page="Update" asp-route-Id="@role.Id">Update</a></td>
			<td>
				<form asp-page-handler="Delete" asp-route-id="@role.Id" method="post">
					<button type="submit" class="btn btn-sm btn-danger">
						Delete
					</button>
				</form>
			</td>
		</tr>
	}
</table>