WebbiSkools.QuizManager/Pages/QuizManager/Question/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
	[Authorize(Roles = "Admin, Edit")]
	public class CreateModel : PageModel
	{
		private readonly IDataAccessMediator<QuestionViewModel> _questionData;
		private readonly IDataAccessMediator<AnswerViewModel> _answerData;
		private readonly IQuizManagementProvider _svc;

		public CreateModel(IDataAccessMediator<QuestionViewModel> questionData, IDataAccessMediator<AnswerViewModel> answerData, IQuizManagementProvider svc)
		{
			_questionData = questionData;
			_answerData = answerData;
			_svc = svc;

		}

		[FromQuery]
		public string QuizId { get; set; }

		public async Task<IActionResult> OnGet()
		{
			SelectList quizesDropdownValues;
			if (QuizId != null)
			{
				quizesDropdownValues = await _svc.GenerateQuizesDropdown(specificIdToSelect: QuizId);

			}
			else
			{
				quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmpty: true);

			}
			ViewData["QuizId"] = quizesDropdownValues;
			return Page();
		}

		[BindProperty]
		public QuestionViewModel Question { get; set; }

		// To protect from overposting attacks, enable the specific properties you want to bind to, for
		// more details, see https://aka.ms/RazorPagesCRUD.
		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				var quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmpty: true);
				ViewData["QuizId"] = quizesDropdownValues;
				return Page();
			}

			foreach(var ans in Question.Answers.ToList())
			{
				if (string.IsNullOrEmpty(ans.Text))
				{
					Question.Answers.Remove(ans);
				}
			}
			if (Question.QuizId == -1)
			{
				Question.Quiz = null;
				Question.QuizId = null;
			}
			await _questionData.AddAsync(Question);

			if (QuizId != null)
			{
				return RedirectToPage("./Index", new { QuizId });
			}
			else
			{
				return RedirectToPage("./Index");
			}
		}
	}
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class DetailsModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _data;
		public DetailsModel(IDataAccessMediator<QuestionViewModel> data)
		{
            _data = data;
		}

		public QuestionViewModel Question { get; set; }
        [FromQuery]
		public int Id { get; set; }

		public async Task OnGet()
        {
            if (Id != 0)
            {
                Question = await _data.GetByIdAsync(Id);
            }
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class EditModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _questionData;
        private readonly IDataAccessMediator<AnswerViewModel> _answerData;
        private readonly IQuizManagementProvider _svc;

        public EditModel(IDataAccessMediator<QuestionViewModel> questionData,
                         IDataAccessMediator<AnswerViewModel> answerData,
                         IQuizManagementProvider svc)
        {
            _svc = svc;
            _questionData = questionData;
            _answerData = answerData;
        }

        [BindProperty]
        public QuestionViewModel Question { get; set; }
        [BindProperty]
        public IList<AnswerViewModel> NewAnswers { get; set; }

        [FromQuery]
		public string QuizId { get; set; }

        [FromQuery]
        public int? QuestionId { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

            Question = await _questionData.GetByIdAsync((int)id);

			if (Question == null)
			{
				return NotFound();
			}
            var selectEmptyIf = Question.QuizId == null && Question.Quiz == null;

            var quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmptyIf);
			ViewData["QuizId"] = quizesDropdownValues;

			return Page();
		}

		// To protect from overposting attacks, enable the specific properties you want to bind to, for
		// more details, see https://aka.ms/RazorPagesCRUD.
		public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Question.QuizId == -1)
            {
                Question.Quiz = null;
                Question.QuizId = null;
            }


            foreach (var ans in NewAnswers.ToList())
            {
                if (string.IsNullOrEmpty(ans.Text))
                {
                    NewAnswers.Remove(ans);
                }
				else
				{
                    await _answerData.AddAsync(ans);
				}
            }
            foreach (var ans in Question.Answers.ToList())
            {
				if (string.IsNullOrEmpty(ans.Text))
				{
					Question.Answers.Remove(ans);
					if (ans.QuestionId != 0)
					{
						await _answerData.DeleteHardAsync(ans.Id);
					}
				}
				else
				{
                    await _answerData.UpdateAsync(ans);
				}
            }

            try
            {
                await _questionData.UpdateAsync(Question);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await QuestionExists(Question.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            if (QuizId != null)
            {
                return RedirectToPage("./Index", new { QuizId });
            }
            else
			{
                return RedirectToPage("./Index");
			}
        }

        public async Task<IActionResult> OnPostDeleteQuestion()
        {
            if (QuestionId != null)
            {
                await _questionData.DeleteHardAsync((int)QuestionId);
            }
            return RedirectToPage("./Index");
        }

        private async ValueTask<bool> QuestionExists(int id)
        {
            return await _questionData.IsAnyWithIdAsync(id);
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class IndexModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _data;
        private readonly IQuizManagementProvider _svc;

        public IndexModel(IDataAccessMediator<QuestionViewModel> data, IQuizManagementProvider svc)
        {
            _data = data;
            _svc = svc;
        }

        public IList<QuestionViewModel> AssignedQuestions { get; set; }
        public IList<QuestionViewModel> NotAssignedQuestions { get; set; }
        public IList<QuestionViewModel> AllQuestions { get; set; }
        [BindProperty]
        public int? QuizId { get; set; }
        [BindProperty]
        public QuestionViewModel Question { get; set; }
        [BindProperty]
        public int? QuestionId { get; set; }

        public async Task OnGetAsync(int? quizId)
        {
            var allQuestions = await _data.GetAsync();
            if (quizId != null)
            {
                ViewData["QuizId"] = quizId;
                AssignedQuestions = allQuestions.Where(x => x.QuizId == quizId).ToList();
                NotAssignedQuestions = allQuestions.Where(x => x.QuizId is null).ToList();
            }
			else
			{
                AllQuestions = allQuestions;
            }
        }

        public async Task<IActionResult> OnPostAddToQuiz()
        {
            var allQuestions = await _data.GetAsync();
            var questionToAssign = allQuestions.FirstOrDefault(m => m.Id == QuestionId);
            questionToAssign.QuizId = QuizId;
            await _data.UpdateAsync(questionToAssign);
            return RedirectToPage("./Index", new { QuizId });
        }

        public async Task<IActionResult> OnPostAssignToCurrentQuiz(int questionId, int quizId)
		{
            await _svc.AssignQuestionToQuiz(quizId, questionId);
            return RedirectToPage("./Index", new { QuizId = quizId });
		}

        public async Task<IActionResult> OnPostUnassignQuestionFromCurrentQuiz(int questionId, int quizId)
        {
            await _svc.UnassignQuestionFromQuiz(quizId, questionId);
            return RedirectToPage("./Index", new { QuizId = quizId });
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;
using WebbiSkools.QuizManager.DAL.Entities.Identity;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize(Roles = "Admin, Edit")]
    public class CreateModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;
        private readonly UserManager<QuizManagerUser> _userMgr;

        public CreateModel(IDataAccessMediator<QuizViewModel> data, UserManager<QuizManagerUser> userMgr)
        {
            _data = data;
            _userMgr = userMgr;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public QuizViewModel Quiz { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //var loggedInUserId = _userMgr.GetUserId(User);
            //Quiz.AuthorId = loggedInUserId;
            await _data.AddAsync(Quiz);

            return RedirectToPage("./Index");
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _quizData;
        private readonly IDataAccessMediator<QuestionViewModel> _questionData;
        private readonly IQuizManagementProvider _svc;

        public DetailsModel(IDataAccessMediator<QuizViewModel> quizData,
                            IDataAccessMediator<QuestionViewModel> questionData,
                            IQuizManagementProvider svc)
        {
            _quizData = quizData;
            _questionData = questionData;
            _svc = svc;
        }

        public QuizViewModel Quiz { get; set; }
        [FromQuery]
        [FromBody]
		public int QuestionId { get; set; }
        [FromQuery]
        [FromBody]
        public int QuizId { get; set; }

		public async Task<IActionResult> OnGetAsync()
        {
            if (QuizId == 0)
            {
                return NotFound();
            }

            Quiz = await _quizData.GetByIdAsync(QuizId);

            if (Quiz == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostUnassignQuestionFromCurrentQuiz(int questionId, int quizId)
        {
            await _svc.UnassignQuestionFromQuiz(quizId, questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }

        public async Task<IActionResult> OnPostAssignToCurrentQuiz(int questionId, int quizId)
        {
            await _svc.AssignQuestionToQuiz(quizId, questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }

        public async Task<IActionResult> OnPostHardDeleteQuestion(int questionId, int quizId)
        {
            await _questionData.DeleteHardAsync(questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize(Roles="Admin, Edit")]
    public class EditModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;

        public EditModel(IDataAccessMediator<QuizViewModel> data)
        {
            _data = data;
        }

        [BindProperty]
        public QuizViewModel Quiz { get; set; }
        [FromQuery]
        [FromBody]
		public int? QuizId { get; set; }

		public async Task<IActionResult> OnGetAsync()
        {
            if (QuizId == null)
            {
                return NotFound();
            }

            Quiz = await _data.GetByIdAsync((int)QuizId);

            if (Quiz == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                await _data.UpdateAsync(Quiz);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await EQuizExists(Quiz.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Details", new { QuizId });

        }

        public async Task<IActionResult> OnPostDeleteQuiz()
		{
            if (QuizId != null)
			{
                await _data.DeleteHardAsync((int)QuizId);
			}
            return RedirectToPage("./Index");
		}

        private async ValueTask<bool> EQuizExists(int id)
        {
            return await _data.IsAnyWithIdAsync(id);
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;

        public IndexModel(IDataAccessMediator<QuizViewModel> data)
        {
            _data = data;
        }

        public IList<QuizViewModel> Quiz { get; set; }

        public async Task OnGetAsync()
        {
            Quiz = await _data.GetAsync();
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Details.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Question.DetailsModel
@{
	ViewData["Title"] = "Details";
	var quizId = HttpContext.Request.Query["QuizId"];
}

<div class="card">
	<div class="card-body">
		<h1 class="display-4">Question Details</h1>
		<div>
			<a asp-page="Index" asp-route-QuizId="@quizId">Back to List</a>
		</div>
		<hr class="style-seven" />
		@if (Model.Question.Quiz != null)
		{
			<p><b>From Quiz:</b> @Html.DisplayFor(modelItem => Model.Question.Quiz.Name) </p>
		}
		else
		{
			<p><b>No Quiz</b> is assigned to this question</p>
		}

		<p class="card-text"><b>Question Text: </b>@Html.DisplayFor(modelItem => Model.Question.Text)</p>
	</div>
	<div class="card-footer">
		<partial name="_AnswersTable" model="@Model.Question.Answers" />
	</div>
</div>

WebbiSkools.QuizManager/Pages/QuizManager/Question/Edit.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Question.EditModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager

@{
	var currentUser = await UserManager.GetUserAsync(User);
	var isUserAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
	var isUserEdit = await UserManager.IsInRoleAsync(currentUser, "Edit");
	var isUserView = await UserManager.IsInRoleAsync(currentUser, "View");

	var questionId = HttpContext.Request.Query["id"];
	var quizId = HttpContext.Request.Query["QuizId"];
}

@section Styles {
	<link rel="stylesheet" href="~/css/QuizManager/Question/shared.css" asp-append-version="true" />
}
<div class="card">
	<div class="card-body">


		<h1 class="display-4">Edit</h1>
		<div class="col-12 col-md-6 col-lg-4" id="subMenuBar">
			<a asp-page="./Index" asp-route-QuizId="@quizId">Back to List</a>
			@if (isUserAdmin || isUserEdit)
			{
				<form method="post" asp-route-QuestionId="@Model.Question.Id" asp-page-handler="DeleteQuestion">
					<button id="submitText" class="text-danger" type="submit">Delete</button>
				</form>
			}
		</div>
		<hr class="style-seven" />
		<form method="post">
			<div class="row">
				<div class="col-md-4">
					<div asp-validation-summary="All" class="text-danger"></div>
					<input hidden asp-for="Question.Id" />
					<input hidden asp-for="Question.CreatedOn" />
					<div class="form-group">
						<label asp-for="Question.Text" class="control-label"></label>
						<input asp-for="Question.Text" class="form-control" />
						<span asp-validation-for="Question.Text" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Question.Quiz" class="control-label"></label>
						<select asp-for="Question.QuizId" class="form-control" asp-items="ViewBag.QuizId"></select>
						<span asp-validation-for="Question.Quiz" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" value="Save" class="btn btn-primary" />
					</div>
				</div>
				<div class="col-md-6">
					<div id="subMenuBar">
						<a id="addAnswerBtn" class="text-success">Add Answer</a>
						<a id="removeAnswerBtn" class="text-danger">Remove Answer</a>
					</div>
					<p id="addAnswerMsgBox"></p>
					<hr class="style-two" />
					@for (var i = 0; i < Model.Question.Answers.Count; i++)
					{
						<div id="answer-@i" class="form-group">
							<input type="hidden" asp-for="Question.Answers[i].Id" />
							<input type="hidden" asp-for="Question.Answers[i].QuestionId" />
							<label asp-for="Question.Answers[i].Text" class="control-label"></label>
							<div class="input-group">
								<input asp-for="Question.Answers[i].Text" class="form-control" />
								<div class="input-group-prepend">
									<span class="input-group-text" id="">Correct?</span>
								</div>
								<input asp-for="Question.Answers[i].IsCorrect" onclick="selectOnlyThis(this)" class="form-control isCorrectCheckbox" />
							</div>
							<span asp-validation-for="Question.Answers[i].Text" class="text-danger"></span>
						</div>
					}
					@if (Model.Question?.Answers?.Count <= 5)
					{
						var stillAvailableAnswers = 5 - Model.Question.Answers.Count;
						var canDeleteAnswers = 2 - stillAvailableAnswers;
						<p>You can add @stillAvailableAnswers and delete @canDeleteAnswers more answer(s) </p>
						int counter = 0;
						@for (var i = 5 - stillAvailableAnswers; i < 5; i++)
						{
				<div id="answer-@i" class="form-group">
					<input type="hidden" asp-for="NewAnswers[counter].QuestionId" value="@questionId" class="form-control" />
					<label asp-for="NewAnswers[counter].Text" class="control-label"></label>
					<div class="input-group">
						<input asp-for="NewAnswers[counter].Text" class="form-control" />
						<div class="input-group-prepend">
							<span class="input-group-text" id="">Correct?</span>
						</div>
						<input asp-for="NewAnswers[counter].IsCorrect" onclick="selectOnlyThis(this)" class="form-control isCorrectCheckbox" />
					</div>
					<span asp-validation-for="NewAnswers[counter].Text" class="text-danger"></span>
				</div>
							counter++;
						}
					}
				</div>
			</div>
		</form>
		<span class="answerCount" id="@Model.Question?.Answers?.Count"></span>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	<script src="~/js/QuizManager/Question/shared.js" asp-append-version="true"></script>
	<script src="~/js/QuizManager/Question/edit.js" asp-append-version="true"></script>
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Index.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Question.IndexModel
@{
	ViewData["Title"] = "Question Manager";
	var quizId = HttpContext.Request.Query["QuizId"];
}
<div class="card">
	<div class="card-body">


		<h1 class="display-4">@ViewData["Title"]</h1>
		<div class="col-12 col-md-6 col-lg-4" id="subMenuBar">
				<a asp-page="Create" asp-route-QuizId="@quizId">Create New</a>
				@if (quizId != Microsoft.Extensions.Primitives.StringValues.Empty)
				{
					<a asp-page="../Quiz/Details" asp-route-QuizId="@quizId">Back To Quiz</a>
				}
		</div>
		<hr class="style-seven" />

		@if (quizId != Microsoft.Extensions.Primitives.StringValues.Empty)
		{
			<h1 class="display-4">
				Questions <small>that are assigned to this Quiz</small>
			</h1>
			<partial name="_QuestionsTable" model="Model.AssignedQuestions" />
			<h1 class="display-4">
				Questions <small>that are <b>not</b> assigned to any Quiz</small>
			</h1>
			<partial name="_QuestionsTable" model="Model.NotAssignedQuestions" />
		}
		else
		{
			<h1 class="display-4">
				All Questions
			</h1>
			<partial name="_QuestionsTable" model="Model.AllQuestions" />
		}
	</div>
</div>

WebbiSkools.QuizManager/Pages/QuizManager/Question/_QuestionsTable.cshtml
@model IList<WebbiSkools.QuizManager.BRL.ViewModels.Quiz.QuestionViewModel>

@{ 
	var quizId = ViewBag.QuizId;
	var questionId = 0;
}

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.LabelFor(modelItem => Model.FirstOrDefault().Id)
			</th>	  
			<th>	  
				@Html.LabelFor(modelItem => Model.FirstOrDefault().Text)
			</th>	  
			<th>	  
				@Html.LabelFor(modelItem => Model.FirstOrDefault().LastModified)
			</th>	  
			<th>	  
				@Html.LabelFor(modelItem => Model.FirstOrDefault().CreatedOn)
			</th>
			<th>
				Actions
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Text)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LastModified)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.CreatedOn)
				</td>
				<td>
					<a asp-page="./Details" asp-route-id="@item.Id" asp-route-QuizId="@quizId">Details</a>
					<a asp-page="./Edit" asp-route-id="@item.Id" asp-route-QuizId="@quizId">Edit</a>
					@if (quizId != null && Convert.ToInt32(quizId) != item.QuizId)
					{
						<form method="post"
							  data-ajax="true"
							  data-ajax-confirm="Are you sure you want to assign this question to the current quiz?"
							  data-ajax-loading="#spinner-@item.Id"
							  data-ajax-complete="reload"
							  asp-page-handler="AssignToCurrentQuiz">
							<input type="hidden" asp-for="@questionId" value="@item.Id" />
							<input type="hidden" asp-for="@quizId" />
							<button id="submitText" class="text-success" type="submit">Assign To This Quiz</button>
							<div id="spinner-@item.Id" class="spinner-grow loading-spinner" style="width: 3rem; height: 3rem;" role="status">
								<span class="sr-only">Loading...</span>
							</div>
						</form>
					}
					@if (quizId != null && Convert.ToInt32(quizId) == item.QuizId)
					{
						<form method="post"
							  data-ajax="true"
							  data-ajax-confirm="Are you sure you want to unassign this question from the current quiz?"
							  data-ajax-loading="#spinner-@item.Id"
							  data-ajax-complete="reload"
							  asp-page-handler="UnassignQuestionFromCurrentQuiz">
							<input type="hidden" asp-for="@questionId" value="@item.Id" />
							<input type="hidden" asp-for="@quizId" />
							<button id="submitText" class="text-danger" type="submit">Unassign From This Quiz</button>
							<div id="spinner-@item.Id" class="spinner-grow loading-spinner" style="width: 3rem; height: 3rem;" role="status">
								<span class="sr-only">Loading...</span>
							</div>
						</form>
					}
				</td>
			</tr>
		}
	</tbody>
</table>