WebbiSkools.QuizManager/Pages/QuizManager/Question/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
	[Authorize(Roles = "Admin, Edit")]
	public class CreateModel : PageModel
	{
		private readonly IDataAccessMediator<QuestionViewModel> _questionData;
		private readonly IDataAccessMediator<AnswerViewModel> _answerData;
		private readonly IQuizManagementProvider _svc;

		public CreateModel(IDataAccessMediator<QuestionViewModel> questionData, IDataAccessMediator<AnswerViewModel> answerData, IQuizManagementProvider svc)
		{
			_questionData = questionData;
			_answerData = answerData;
			_svc = svc;

		}

		[FromQuery]
		public string QuizId { get; set; }

		public async Task<IActionResult> OnGet()
		{
			SelectList quizesDropdownValues;
			if (QuizId != null)
			{
				quizesDropdownValues = await _svc.GenerateQuizesDropdown(specificIdToSelect: QuizId);

			}
			else
			{
				quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmpty: true);

			}
			ViewData["QuizId"] = quizesDropdownValues;
			return Page();
		}

		[BindProperty]
		public QuestionViewModel Question { get; set; }

		// To protect from overposting attacks, enable the specific properties you want to bind to, for
		// more details, see https://aka.ms/RazorPagesCRUD.
		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				var quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmpty: true);
				ViewData["QuizId"] = quizesDropdownValues;
				return Page();
			}

			foreach(var ans in Question.Answers.ToList())
			{
				if (string.IsNullOrEmpty(ans.Text))
				{
					Question.Answers.Remove(ans);
				}
			}
			if (Question.QuizId == -1)
			{
				Question.Quiz = null;
				Question.QuizId = null;
			}
			await _questionData.AddAsync(Question);

			if (QuizId != null)
			{
				return RedirectToPage("./Index", new { QuizId });
			}
			else
			{
				return RedirectToPage("./Index");
			}
		}
	}
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class DetailsModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _data;
		public DetailsModel(IDataAccessMediator<QuestionViewModel> data)
		{
            _data = data;
		}

		public QuestionViewModel Question { get; set; }
        [FromQuery]
		public int Id { get; set; }

		public async Task OnGet()
        {
            if (Id != 0)
            {
                Question = await _data.GetByIdAsync(Id);
            }
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class EditModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _questionData;
        private readonly IDataAccessMediator<AnswerViewModel> _answerData;
        private readonly IQuizManagementProvider _svc;

        public EditModel(IDataAccessMediator<QuestionViewModel> questionData,
                         IDataAccessMediator<AnswerViewModel> answerData,
                         IQuizManagementProvider svc)
        {
            _svc = svc;
            _questionData = questionData;
            _answerData = answerData;
        }

        [BindProperty]
        public QuestionViewModel Question { get; set; }
        [BindProperty]
        public IList<AnswerViewModel> NewAnswers { get; set; }

        [FromQuery]
		public string QuizId { get; set; }

        [FromQuery]
        public int? QuestionId { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

            Question = await _questionData.GetByIdAsync((int)id);

			if (Question == null)
			{
				return NotFound();
			}
            var selectEmptyIf = Question.QuizId == null && Question.Quiz == null;

            var quizesDropdownValues = await _svc.GenerateQuizesDropdown(selectEmptyIf);
			ViewData["QuizId"] = quizesDropdownValues;

			return Page();
		}

		// To protect from overposting attacks, enable the specific properties you want to bind to, for
		// more details, see https://aka.ms/RazorPagesCRUD.
		public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Question.QuizId == -1)
            {
                Question.Quiz = null;
                Question.QuizId = null;
            }


            foreach (var ans in NewAnswers.ToList())
            {
                if (string.IsNullOrEmpty(ans.Text))
                {
                    NewAnswers.Remove(ans);
                }
				else
				{
                    await _answerData.AddAsync(ans);
				}
            }
            foreach (var ans in Question.Answers.ToList())
            {
				if (string.IsNullOrEmpty(ans.Text))
				{
					Question.Answers.Remove(ans);
					if (ans.QuestionId != 0)
					{
						await _answerData.DeleteHardAsync(ans.Id);
					}
				}
				else
				{
                    await _answerData.UpdateAsync(ans);
				}
            }

            try
            {
                await _questionData.UpdateAsync(Question);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await QuestionExists(Question.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            if (QuizId != null)
            {
                return RedirectToPage("./Index", new { QuizId });
            }
            else
			{
                return RedirectToPage("./Index");
			}
        }

        public async Task<IActionResult> OnPostDeleteQuestion()
        {
            if (QuestionId != null)
            {
                await _questionData.DeleteHardAsync((int)QuestionId);
            }
            return RedirectToPage("./Index");
        }

        private async ValueTask<bool> QuestionExists(int id)
        {
            return await _questionData.IsAnyWithIdAsync(id);
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Question/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Question
{
    [Authorize(Roles = "Admin, Edit")]
    public class IndexModel : PageModel
    {
        private readonly IDataAccessMediator<QuestionViewModel> _data;
        private readonly IQuizManagementProvider _svc;

        public IndexModel(IDataAccessMediator<QuestionViewModel> data, IQuizManagementProvider svc)
        {
            _data = data;
            _svc = svc;
        }

        public IList<QuestionViewModel> AssignedQuestions { get; set; }
        public IList<QuestionViewModel> NotAssignedQuestions { get; set; }
        public IList<QuestionViewModel> AllQuestions { get; set; }
        [BindProperty]
        public int? QuizId { get; set; }
        [BindProperty]
        public QuestionViewModel Question { get; set; }
        [BindProperty]
        public int? QuestionId { get; set; }

        public async Task OnGetAsync(int? quizId)
        {
            var allQuestions = await _data.GetAsync();
            if (quizId != null)
            {
                ViewData["QuizId"] = quizId;
                AssignedQuestions = allQuestions.Where(x => x.QuizId == quizId).ToList();
                NotAssignedQuestions = allQuestions.Where(x => x.QuizId is null).ToList();
            }
			else
			{
                AllQuestions = allQuestions;
            }
        }

        public async Task<IActionResult> OnPostAddToQuiz()
        {
            var allQuestions = await _data.GetAsync();
            var questionToAssign = allQuestions.FirstOrDefault(m => m.Id == QuestionId);
            questionToAssign.QuizId = QuizId;
            await _data.UpdateAsync(questionToAssign);
            return RedirectToPage("./Index", new { QuizId });
        }

        public async Task<IActionResult> OnPostAssignToCurrentQuiz(int questionId, int quizId)
		{
            await _svc.AssignQuestionToQuiz(quizId, questionId);
            return RedirectToPage("./Index", new { QuizId = quizId });
		}

        public async Task<IActionResult> OnPostUnassignQuestionFromCurrentQuiz(int questionId, int quizId)
        {
            await _svc.UnassignQuestionFromQuiz(quizId, questionId);
            return RedirectToPage("./Index", new { QuizId = quizId });
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;
using WebbiSkools.QuizManager.DAL.Entities.Identity;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize(Roles = "Admin, Edit")]
    public class CreateModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;
        private readonly UserManager<QuizManagerUser> _userMgr;

        public CreateModel(IDataAccessMediator<QuizViewModel> data, UserManager<QuizManagerUser> userMgr)
        {
            _data = data;
            _userMgr = userMgr;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public QuizViewModel Quiz { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //var loggedInUserId = _userMgr.GetUserId(User);
            //Quiz.AuthorId = loggedInUserId;
            await _data.AddAsync(Quiz);

            return RedirectToPage("./Index");
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _quizData;
        private readonly IDataAccessMediator<QuestionViewModel> _questionData;
        private readonly IQuizManagementProvider _svc;

        public DetailsModel(IDataAccessMediator<QuizViewModel> quizData,
                            IDataAccessMediator<QuestionViewModel> questionData,
                            IQuizManagementProvider svc)
        {
            _quizData = quizData;
            _questionData = questionData;
            _svc = svc;
        }

        public QuizViewModel Quiz { get; set; }
        [FromQuery]
        [FromBody]
		public int QuestionId { get; set; }
        [FromQuery]
        [FromBody]
        public int QuizId { get; set; }

		public async Task<IActionResult> OnGetAsync()
        {
            if (QuizId == 0)
            {
                return NotFound();
            }

            Quiz = await _quizData.GetByIdAsync(QuizId);

            if (Quiz == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostUnassignQuestionFromCurrentQuiz(int questionId, int quizId)
        {
            await _svc.UnassignQuestionFromQuiz(quizId, questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }

        public async Task<IActionResult> OnPostAssignToCurrentQuiz(int questionId, int quizId)
        {
            await _svc.AssignQuestionToQuiz(quizId, questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }

        public async Task<IActionResult> OnPostHardDeleteQuestion(int questionId, int quizId)
        {
            await _questionData.DeleteHardAsync(questionId);
            return RedirectToPage("./Details", new { QuizId = quizId });
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize(Roles="Admin, Edit")]
    public class EditModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;

        public EditModel(IDataAccessMediator<QuizViewModel> data)
        {
            _data = data;
        }

        [BindProperty]
        public QuizViewModel Quiz { get; set; }
        [FromQuery]
        [FromBody]
		public int? QuizId { get; set; }

		public async Task<IActionResult> OnGetAsync()
        {
            if (QuizId == null)
            {
                return NotFound();
            }

            Quiz = await _data.GetByIdAsync((int)QuizId);

            if (Quiz == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                await _data.UpdateAsync(Quiz);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await EQuizExists(Quiz.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Details", new { QuizId });

        }

        public async Task<IActionResult> OnPostDeleteQuiz()
		{
            if (QuizId != null)
			{
                await _data.DeleteHardAsync((int)QuizId);
			}
            return RedirectToPage("./Index");
		}

        private async ValueTask<bool> EQuizExists(int id)
        {
            return await _data.IsAnyWithIdAsync(id);
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbiSkools.QuizManager.BRL.DataAccessMediators.Abstractions;
using WebbiSkools.QuizManager.BRL.Services.Abstractions;
using WebbiSkools.QuizManager.BRL.ViewModels.Quiz;

namespace WebbiSkools.QuizManager.Pages.QuizManager.Quiz
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IDataAccessMediator<QuizViewModel> _data;

        public IndexModel(IDataAccessMediator<QuizViewModel> data)
        {
            _data = data;
        }

        public IList<QuizViewModel> Quiz { get; set; }

        public async Task OnGetAsync()
        {
            Quiz = await _data.GetAsync();
        }
    }
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Create.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Quiz.CreateModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager

@{
	ViewData["Title"] = "Create";
}
<div class="card">
	<div class="card-body">
		<h1 class="display-4">Create a new Quiz</h1>
		<hr class="style-seven" />
		<div class="row">
			<div class="col-md-4">
				<form method="post">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<label asp-for="Quiz.Name" class="control-label"></label>
						<input asp-for="Quiz.Name" class="form-control" />
						<span asp-validation-for="Quiz.Name" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" value="Create" class="btn btn-primary" />
					</div>
				</form>
			</div>
		</div>

		<div>
			<a asp-page="Index">Back to List</a>
		</div>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Details.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Quiz.DetailsModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager
@{
	var currentUser = await UserManager.GetUserAsync(User);
	var isUserAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
	var isUserEdit = await UserManager.IsInRoleAsync(currentUser, "Edit");
	var isUserView = await UserManager.IsInRoleAsync(currentUser, "View");

	ViewData["Title"] = "Details";
}

@section Styles {
	<link rel="stylesheet" href="~/css/QuizManager/Quiz/details.css" />
}

<div class="container">
	<div class="card">
		<div class="card-body">


			<!-- Portfolio Item Heading -->
			<h1 class="my-4">
				@Html.DisplayFor(model => model.Quiz.Name)
				<small>{ ID: @Html.DisplayFor(model => model.Quiz.Id) }</small>
			</h1>

			<!-- Portfolio Item Row -->
			<div class="row">

				<div class="col-md-8">
					<img class="img-fluid" src="https://www.insidehighered.com/sites/default/server_files/media/teaching%20and%20research.jpg" alt="">
				</div>

				<div class="col-md-4">
					<h3 class="my-3">Quiz Description</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
					<h3 class="my-3">Quiz Details</h3>
					<ul>
						<li>
							@Html.DisplayNameFor(model => model.Quiz.CreatedOn) : @Html.DisplayFor(model => model.Quiz.CreatedOn)
						</li>
						<li>
							@Html.DisplayNameFor(model => model.Quiz.LastModified) : @Html.DisplayFor(model => model.Quiz.LastModified)
						</li>
						<li>
							@Html.DisplayNameFor(model => model.Quiz.Questions) : @Html.DisplayFor(model => model.Quiz.Questions.Count)
						</li>
					</ul>
					<h3 class="my-3">Actions</h3>
					<ul>
						@if (isUserAdmin || isUserEdit)
						{
							<li><a asp-page="./Edit" asp-route-QuizId="@Model.Quiz.Id">Edit Quiz</a></li>
							<li><a asp-page="../Question/Index" asp-route-QuizId="@Model.Quiz.Id">Manage Questions</a></li>
						}
						<li><a asp-page="./Index">Back to List</a></li>
					</ul>
				</div>

			</div>

			<div class="row justify-content-center">
				<div class="col-md-10">
					<partial name="_QuestionsInQuizTable" model="Model" />
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script src="~/js/QuizManager/Quiz/details.js"></script>
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Edit.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Quiz.EditModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager
@{
	var currentUser = await UserManager.GetUserAsync(User);
	var isUserAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
	var isUserEdit = await UserManager.IsInRoleAsync(currentUser, "Edit");
	var isUserView = await UserManager.IsInRoleAsync(currentUser, "View"); 
	
	ViewData["Title"] = "Edit";
}

<div class="card">
	<div class="card-body">
		<h1 class="display-4">Edit the Quiz</h1>
		<div class="col-12 col-md-6 col-lg-4" id="subMenuBar">
			<a id="someId" asp-page="./Details" asp-route-QuizId="@Model.Quiz.Id">Back to Details page</a>
			@if (isUserAdmin || isUserEdit)
			{
				<form method="post" asp-route-QuizId="@Model.Quiz.Id" asp-page-handler="DeleteQuiz">
					<button id="submitText" class="text-danger" type="submit">Delete</button>
				</form>
			}
		</div>
		<hr class="style-seven" />
		<div class="row">
			<div class="col-md-4">
				<form method="post">
					<input hidden asp-for="Quiz.Id" />
					<input hidden asp-for="Quiz.CreatedOn" />
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<label asp-for="Quiz.Name" class="control-label"></label>
						<input asp-for="Quiz.Name" class="form-control" />
						<span asp-validation-for="Quiz.Name" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" value="Save" class="btn btn-primary" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	<script src="~/js/QuizManager/Quiz/edit.js" asp-append-version="true"></script>

}

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/Index.cshtml
@page
@model WebbiSkools.QuizManager.Pages.QuizManager.Quiz.IndexModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager
@{
	var currentUser = await UserManager.GetUserAsync(User);
	var isUserAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
	var isUserEdit = await UserManager.IsInRoleAsync(currentUser, "Edit");
	var isUserView = await UserManager.IsInRoleAsync(currentUser, "View");

	ViewData["Title"] = "Quizes";
}

<div class="card">
	<div class="card-body">
		<h1 class="display-4">@ViewData["Title"]</h1>
		<div class="col-12 col-md-6 col-lg-4" id="subMenuBar">
			@if (isUserAdmin || isUserEdit)
			{
				<a asp-page="Create">Create New</a>
			}
		</div>

		<hr class="style-seven" />

		<table class="table">
			<thead>
				<tr>
					<th>
						@Html.LabelFor(modelItem => Model.Quiz.FirstOrDefault().Name)
					</th>
					<th>
						@Html.LabelFor(modelItem => Model.Quiz.FirstOrDefault().LastModified)
					</th>
					<th>
						@Html.LabelFor(modelItem => Model.Quiz.FirstOrDefault().CreatedOn)
					</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model.Quiz)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.Name)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LastModified)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.CreatedOn)
						</td>
						<td>
							<a asp-page="./Details" asp-route-QuizId="@item.Id">Details</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

WebbiSkools.QuizManager/Pages/QuizManager/Quiz/_QuestionsInQuizTable.cshtml
@model WebbiSkools.QuizManager.Pages.QuizManager.Quiz.DetailsModel
@inject UserManager<WebbiSkools.QuizManager.DAL.Entities.Identity.QuizManagerUser> UserManager
@{
	var currentUser = await UserManager.GetUserAsync(User);
	var isUserAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
	var isUserEdit = await UserManager.IsInRoleAsync(currentUser, "Edit");
	var isUserView = await UserManager.IsInRoleAsync(currentUser, "View");
}

@if (Model.Quiz.Questions?.Count > 0)
{
	<h1 class="my-4">
		Questions <small>assigned to this Quiz</small>
	</h1>
}
else
{
	<div class="text-center">
		<h1 class="my-4">
			No Questions are assigned to this Quiz
		</h1>
		<p class="lead">Hit 'Manage Questions' above to add some!</p>
	</div>
}


@{
	var cter = 1;
	foreach (var item in Model.Quiz.Questions)
	{
		<div class="card">
			<div class="card-header"></div>
			<div class="card-body">
				<h5 class="card-title">Question #@(cter++)</h5>
				<p class="card-text">@Html.DisplayFor(modelItem => item.Text)</p>
				<div class="row">
					<div class="col-md-6" id="subMenuBar">
						@if (isUserAdmin || isUserEdit || isUserView)
						{
							<a id="showHideBtn-@item.Id" class="card-link text-success" onclick="toggleAnswers(@item.Id)">View Answers</a>
						}
						@if (isUserAdmin || isUserEdit)
						{
							<form method="post"
								  data-ajax="true"
								  data-ajax-confirm="Are you sure you want to unassign this question?"
								  data-ajax-loading="#spinner-@item.Id"
								  data-ajax-complete="reload"
								  asp-page-handler="UnassignQuestionFromCurrentQuiz">
								<input type="hidden" asp-for="QuestionId" value="@item.Id" />
								<input type="hidden" asp-for="QuizId" />
								<button id="submitText" class="card-link text-danger" type="submit">Unnasign From Quiz</button>
							</form>
							<form method="post"
								  data-ajax="true"
								  data-ajax-confirm="Are you sure you want to delete this question?"
								  data-ajax-loading="#spinner-@item.Id"
								  data-ajax-complete="reload" asp-page-handler="HardDeleteQuestion">
								<input type="hidden" asp-for="QuizId" />
								<input type="hidden" asp-for="QuestionId" value="@item.Id" />
								<button id="submitText" class="card-link text-danger" type="submit">Delete</button>
							</form>
							<div id="spinner-@item.Id" class="spinner-grow loading-spinner" style="width: 3rem; height: 3rem;" role="status">
								<span class="sr-only">Loading...</span>
							</div>
						}
					</div>
				</div>
				<div class="row">
					<div class="answers col-md-12" id="answers-@item.Id">
						<partial name="_AnswersTable" model="@item.Answers" />
					</div>
				</div>
			</div>

		</div>
	}
}